language: node_js
cache:
  directories:
    - node_modules
script:
  - npm install -g knex
  - knex migrate:latest
  - npm test
  - .travis/deploy.sh
after_success:
  - .travis/notify.sh "1"
after_failure:
  - .travis/notify.sh "0"
