language: node_js
script:
  - npm install -g knex
  - knex migrate:latest
  - npm test
after_success: |
  if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${SLACK_LOG_WEBHOOK}" != "" ]; then
    echo "sending notification to slack"
    npm run log --username=travis-ci --emoji=satellite_antenna --text=":sunglasses: Travis build success https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}" --webhook="${SLACK_LOG_WEBHOOK}"
  else
      echo "skipping slack log notification because this is a pull request or SLACK_LOG_WEBHOOK is not configured"
  fi
  echo "creating build package"
  npm run build --file="spark-`npm view spark version`-${TRAVIS_BRANCH}-${TRAVIS_BUILD_ID}.tar.gz"
  if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${SLACK_API_TOKEN}" != "" ]; then
    echo "uploading build package to slack"
    npm run upload --file="spark-`npm view spark version`-${TRAVIS_BRANCH}-${TRAVIS_BUILD_ID}.tar.gz" --text="Travis build for ${TRAVIS_REPO_SLUG}, branch ${TRAVIS_BRANCH}, build number ${TRAVIS_BUILD_NUMBER}, build id ${TRAVIS_BUILD_ID}" --token="${SLACK_API_TOKEN}"
  else
    echo "skipping upload of build package to slack because this is a pull request or SLACK_API_TOKEN is not configured"
  fi
after_failure: |
  if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${SLACK_LOG_WEBHOOK}" != "" ]; then
    echo "sending notification to slack"
    npm run log --username=travis-ci --emoji=satellite_antenna --text=":scream: Travis build failure https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID}" --webhook="${SLACK_LOG_WEBHOOK}"
  else
    echo "skipping slack log notification because this is a pull request or SLACK_LOG_WEBHOOK is not configured"
  fi
